version: "3.7"

services:
  postgres:
    build: postgres
    container_name: postgres
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - project_network

  postgres-cdc-stream:
    build: postgres_cdc
    depends_on:
      - postgres
    container_name: postgres-cdc-stream
    env_file:
      - .env
    networks:
      - project_network

networks:
  project_network:

volumes:
  database:
